# Generated by Django 5.1.1 on 2024-09-19 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        null=True, upload_to="", verbose_name="Аватар пользователя"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "user"), (1, "oragizator"), (2, "depart")],
                        default=0,
                        help_text="0 - пользователь, 1 - организатор, 2 - департамент",
                        verbose_name="Роль пользователя",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
