# Generated by Django 5.1.1 on 2024-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.IntegerField(
                choices=[(0, "user"), (1, "oragizator"), (2, "depart")],
                default=0,
                help_text="0 - пользователь, 1 - организатор, 2 - департамент",
                verbose_name="Роль пользователя",
            ),
        ),
    ]
