# Generated by Django 5.1.1 on 2024-09-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
    ]
