# Generated by Django 5.1.1 on 2024-09-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
    ]
