version: "3"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  db:
    image: 'postgres:latest'
    environment: 
        POSTGRES_DB: db
        POSTGRES_USER: developer
        POSTGRES_PASSWORD: Passw0rd33
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    volumes:
      - ./kernel:/app
    env_file:
      - ./kernel/.env
    build: ./kernel
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - db
      

  dev-nginx:
    image: staticfloat/nginx-certbot
    depends_on:
      - web 
    volumes:
      - ./kernel/static:/var/www/html/static
      - ./kernel/media:/media
      - ./nginx/dev.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
#      - www-html:/var/www/html
    environment:
      CERTBOT_EMAIL: adrian@makridenko.ru
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: unless-stopped

volumes:
  static:
  letsencrypt:
  www-html:
