# Generated by Django 5.1.1 on 2024-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="rating",
            field=models.FloatField(max_length=5.0, null=True, verbose_name="Рейтинг"),
        ),
    ]
