# Generated by Django 5.1.1 on 2024-09-19 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_events_is_archive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="guests",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="event_guess",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Гости на событии",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="organizer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_organaser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор события",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="rating",
            field=models.FloatField(null=True, verbose_name="Рейтинг"),
        ),
    ]
