# Generated by Django 5.1.1 on 2024-09-19 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_events_guests_events_organizer_alter_events_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_organaser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор события",
            ),
        ),
    ]
