# Generated by Django 5.1.1 on 2024-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="title",
        ),
        migrations.AddField(
            model_name="reviews",
            name="rate",
            field=models.FloatField(default=5.0, verbose_name="Оценка события"),
        ),
    ]
