version: '3.7'

services:
  db:
    image: 'postgres:latest'
    shm_size: '256m'
    restart: on-failure
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_DATABASES=16


  kernel:
    user: vscode
    env_file:
      - ../.env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '..:/workspace:cached'
    ports:
      - '5000:5000'
    command: sleep infinity
