# Generated by Django 5.1.1 on 2024-09-19 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0006_alter_events_organizer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(max_length=16, verbose_name="Код группы"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.events",
                        verbose_name="Ивент",
                    ),
                ),
                (
                    "party_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_owmer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лидер группы",
                    ),
                ),
                (
                    "soopartyes",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Участники группы"
                    ),
                ),
            ],
        ),
    ]
