# Generated by Django 5.1.1 on 2024-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="invite_code",
            field=models.CharField(
                max_length=16, unique=True, verbose_name="Код группы"
            ),
        ),
    ]
